#ifndef TABLE_VIEW_HELPER
#define TABLE_VIEW_HELPER


#define GET_TABLE(CLASS_NAME)ui.m_tbl##CLASS_NAME
#define CALL_INIT_FUNCTION(CLASS_NAME) init##CLASS_NAME()

#define DECLARE_INIT_FUNCTION_FOR_CLASS(CLASS_NAME)	bool CALL_INIT_FUNCTION(CLASS_NAME)
#define IMPLEMENT_INIT_FUNCTION_FOR_CLASS(PARENT,CLASS_NAME) bool PARENT::CALL_INIT_FUNCTION(CLASS_NAME)

#define INSTALL_EVENT_FILTER(CLASS_NAME)\
	GET_TABLE(CLASS_NAME)->installEventFilter(this);

#define SET_EVENT_TABLE(PARENT,CLASS_NAME)	m_mEventTable[GET_TABLE(CLASS_NAME)]=PARENT->m_pMod##CLASS_NAME

#define GET_TABLE_MODEL(PARENT,CLASS_NAME)	PARENT->m_pMod##CLASS_NAME


#define CALL_UPDATE_FUNCTION(CLASS_NAME)							update##CLASS_NAME(const QModelIndex & current, const QModelIndex & previous)
#define DECLARE_UPDATE_FUNCTION_FOR_CLASS(CLASS_NAME)				void CALL_UPDATE_FUNCTION(CLASS_NAME)
#define IMPLEMENT_UPDATE_FUNCTION_FOR_CLASS(PARENT,CLASS_NAME)		void PARENT::CALL_UPDATE_FUNCTION(CLASS_NAME)
#define CONNECT_ROW_CHAHANGED_SLOT(CLASS_PARENT,SLOT_FUNCTION)		connect(GET_TABLE(CLASS_PARENT)->selectionModel(),SIGNAL(currentRowChanged(const QModelIndex &,const QModelIndex &)),this,SLOT(SLOT_FUNCTION));
#define CONNECT_ACTION_TRIGGERED_SLOT(ACTION, SLOT_FUNC) connect(ACTION, &QAction::triggered, this, &kvmrt2_media_editor::SLOT_FUNC);

#define SET_SELECTION_BEHAVIOR(CLASS_NAME,BEHAVIOR)		GET_TABLE(CLASS_NAME)->setSelectionBehavior(BEHAVIOR);
#define SET_SELECTION_MODE(CLASS_NAME,SELECTIONMODE)	GET_TABLE(CLASS_NAME)->setSelectionMode(SELECTIONMODE);
#define SET_EDIT_TRIGGERS(CLASS_NAME,TRIGGERMODE)		GET_TABLE(CLASS_NAME)->setEditTriggers(TRIGGERMODE);



#define SET_DRAG_AND_DROP_ENABLED(CLASS_NAME)			GET_TABLE(CLASS_NAME)->setDragEnabled(true);	GET_TABLE(CLASS_NAME)->setAcceptDrops(true);	GET_TABLE(CLASS_NAME)->setDropIndicatorShown(true);	GET_TABLE(CLASS_NAME)->setDragDropMode(QAbstractItemView::InternalMove);


#define SET_MODEL_FOR_TABLE_VIEW(CLASS_NAME,MODEL_PARENT)	ui.m_tbl##CLASS_NAME->setModel((QAbstractItemModel*)MODEL_PARENT->m_pMod##CLASS_NAME.get());


#define SET_SELECTION_CHANGED_FOR_TABLE(PARENT,CLASS_NAME,SLOT_FUNCTION)		connect((QObject*)PARENT->m_pMod##CLASS_NAME.get(),SIGNAL(selectionChanged(int,int)),this,SLOT(SLOT_FUNCTION));

#define SET_HIDE_TABLE_COLUMN(CLASS_NAME, COLUMN) \
	GET_TABLE(CLASS_NAME)->horizontalHeader()->hideSection(COLUMN);

#define SET_HIDE_TABLE_COLUMN_RANGE(CLASS_NAME, START_COL, LAST_COL) \
	for(int i = START_COL; i <= LAST_COL; ++i) \
	{ SET_HIDE_TABLE_COLUMN(CLASS_NAME, i); }
#endif