#ifndef DEFINE_SETTINGS
#define DEFINE_SETTINGS

#include <tchar.h>
#include <windows.h>
#include "MSettingsStorage.h"
#include "MSettingsStorageIniFile.h"
#include "MSettingsStorageRegistry.h"

#include <vector>

#define SERVER_PATH_INI_SECTION		_T("PATH")
#define SERVER_ADDRESS_INI_SECTION	_T("ADDRESS")
#define SERVER_SCRIPT_INI_SECTION	_T("SCRIPT")
#define SERVER_PORT_INI_SECTION		_T("PORT")
#define SERVER_VOLUME_INI_SECTION	_T("VOLUME")
#define SERVER_LED_INI_SECTION		_T("LED")
#define SERVER_MISC_INI_SECTION		_T("MISC")
#define SERVER_IPC_SECTION			_T("IPC")
#define SERVER_MEM_SECTION			_T("MEMORY_MAP")
#define SERVER_RAD_SECTION			_T("RADSETTINGS")
#define SERVER_LED_SECTION			_T("LEDSETTINGS")
#define SERVER_COMM_SECTION			_T("COMMSETTINGS")
#define SERVER_SETTINGS_FILE		_T("SETTINGS.INI")
#define SERVER_IPADDRESS_TABLE		_T("IPTABLE.INI")
#define SERVER_INTERNAL_DEVICE_PORT_SECTION	_T("INTERNAL_DEVICE_PORTS")

#define dim(x) (sizeof(x)/sizeof(x[0]))

using namespace Mortimer;

class CPathSettings	:public CSettings
{
public:
	TCHAR FONT_FILE_SAVE_PATH[256];
	TCHAR AUDIO_FILE_SAVE_PATH[256];
	TCHAR VIDEO_FILE_SAVE_PATH[256];
	TCHAR DATABASE_FILE_PATH[256];

	BEGIN_SETTING_MAP(CPathSettings)
		SETTING_ITEM_SZ_DEFAULT(AUDIO_FILE_SAVE_PATH,_countof(AUDIO_FILE_SAVE_PATH),_T("C:\\PAPIS_ME\\Audio"))
		SETTING_ITEM_SZ_DEFAULT(FONT_FILE_SAVE_PATH,_countof(FONT_FILE_SAVE_PATH),_T("C:\\PAPIS_ME\\Font"))
		SETTING_ITEM_SZ_DEFAULT(VIDEO_FILE_SAVE_PATH,_countof(VIDEO_FILE_SAVE_PATH),_T("C:\\PAPIS_ME\\Video"))
		SETTING_ITEM_SZ_DEFAULT(DATABASE_FILE_PATH,_countof(DATABASE_FILE_PATH),_T("C:\\PAPIS_ME"))
	END_SETTING_MAP()
};


#endif